# Generated by Django 3.2.4 on 2024-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240421_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='callback_url',
            field=models.CharField(default=1000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='INR', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_amount',
            field=models.DecimalField(decimal_places=2, default='10000', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_merchant_key',
            field=models.CharField(default='abcd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
