# Generated by Django 3.2.4 on 2024-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('in_transit', 'In Transit'), ('return_in_progress', 'Refund Delivery in Progress'), ('returned_to_seller', 'Returned To Seller'), ('cancelled', 'Cancelled')], default='in_transit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refund_pending', 'Refund Pending'), ('completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
